[PROD-390] Deploy triggers build on member userpool repos
JB-AssetChain/inf.member.hooks pull request #4
Opened 2021-12-22 04:34 UTC by semiautomatixfu

[PROD-390]

- if `inf.member.hooks` is rebuilt it will trigger a build on other listed Jenkins jobs
- at the moment, this should log an error because `inf.member.fu` has not been made available to Jenkins

2021-12-22 05:10 UTC, tleed5 requested changes

2021-12-22 05:10 UTC, tleed5 commented on Jenkinsfile
> +                        )
Shouldn't this have a `parameters` option for `DEPLOY_PROD` / `DEPLOY_DEV` ?

2021-12-22 05:10 UTC, tleed5 commented on src/config/Config.ts
>  // @flow
Are the`// @flow` needed anymore since it's now typescript?

2021-12-22 06:00 UTC, semiautomatixfu commented on src/config/Config.ts
>  // @flow
:+1:

2021-12-22 06:01 UTC, semiautomatixfu commented on Jenkinsfile
> +                        )
:open_mouth: didn't even notice that they were `params` and not `env`

2021-12-23 01:18 UTC, tleed5 approved these changes

2021-12-23 01:24 UTC, merged